### PR TITLE
Fixed server side rendering issue with feed

### LINKED ISSUE #1141: Feed Layout shift on page load feels "broken"
For a split second when loading the feed, the layout is not rendered correctly. This may feel broken to the user.

### PR DESCRIPTION
**Pull request by thomas-vu**
- Fixes #1141

### CODE REVIEW

File: components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx [hunk 1]
```diff
@@ -248,7 +252,7 @@ function UnifiedDocFeedContainer({
           />
         </div>
       </div>
-      {Boolean(unifiedDocsLoading) ? (
+      {unifiedDocsLoading || isServer() ? (
```
Comment (yattias) [inline components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx:255]: Do you still need the `unifiedDocsLoading` given that you have an `isServer()` check now?

Comment (thomas-vu) [reply components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx:255]: Yeah.

File: components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx [hunk 2]
```diff
@@ -75,6 +75,10 @@ function UnifiedDocFeedContainer({
     hotV2: router.query?.hot_v2 == "true",
   };
 
+  useEffect(() => {
```
Comment (lightninglu10) [inline components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx:78]: can we remove this state and set it back to what we had before with the useState(false), or do we need it?

Comment (thomas-vu) [reply components/UnifiedDocFeed/UnifiedDocFeedContainer.tsx:78]: We need it to avoid a strange bug with the first 3 cards. Not sure why this happens.

Screen Shot 2022-04-07 at 7 55 54 PM

**Review by yattias — APPROVED** [review]
LGTM
