### PR TITLE
Various bug fixes

### LINKED ISSUE #1148: Issues with search after feed card refactor
Slack conversation: https://researchhub-community.slack.com/archives/C01C3M9S283/p1649141838805989

**Issues:**
- Date incorrect (always shows today's date)
- Submitter of the paper does not show up

### LINKED ISSUE #1150: "Share this discussion" broken
See slack https://researchhub-community.slack.com/archives/C01C3M9S283/p1649163253712489

### PR DESCRIPTION
**Pull request by thomas-vu**
**What?**

- Fixed bug where feed cleared upon clicking logo
- Closes #1148
- Closes #1150
- Fixed feed cards for search
- Updated DOI css on post page

### CODE REVIEW

**Review by lightninglu10 — APPROVED** [review]

**Comment by lightninglu10** [comment]
LGTM

File: components/DiscussionPostMetadata.js [hunk 1]
```diff
@@ -256,6 +248,12 @@ const DiscussionPostMetadata = (props) => {
   return (
     <div className={css(styles.container, containerStyle && containerStyle)}>
       <ContentSupportModal />
+      <ShareModal
+        isOpen={shareModalIsOpen}
+        setIsOpen={setShareModalIsOpen}
+        title={"Share this discussion"}
+        url={window.location.href + "#comments"}
```
Comment (yattias) [inline components/DiscussionPostMetadata.js:255]: This could throw an error if we do a refactor because `window` is not defined on the server.
Could you see if you can use `${process.env.HOST}/router.pathname#comments` instead? The `HOST` env var is available on all environments.

Comment (thomas-vu) [reply components/DiscussionPostMetadata.js]: Good catch, I updated it.
